version: '3.8'

services:
  pzsp2-db:
    image: mysql
    container_name: pzsp2-db-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passwd
    expose:
      - "3306"
    volumes:
      - pzsp2-db:/var/lib/mysql
      - ./fITness_db/db_init:/docker-entrypoint-initdb.d

  backend:
    image: python:3.12
    build:
      context: ./fITness_backend
      dockerfile: Dockerfile
    container_name: pzsp2-backend-app
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: pzsp2-db
      MYSQL_PORT: "3306"
      MYSQL_USER: root
      MYSQL_PASSWORD: passwd
      MYSQL_DB: pzsp2-db
    volumes:
      - ./fITness_backend:/app
    depends_on:
      - pzsp2-db
    links:
      - pzsp2-db

  frontend:
    image: node:14.17.3
    container_name: pzsp2-frontend
    build:
      context: ./client-app-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client-app-frontend:/frontend

volumes:
  pzsp2-db:
